In [65]:
import pandas as pd
import os

In [82]:
input_file_path = "/home/user2/Documents/PBL-Bihar/mip-report/task-report/raw"

In [83]:
csv_files = [f for f in os.listdir(input_file_path) if f.endswith('.csv')]
if not csv_files:
    raise ValueError("No CSV files found in the input directory.")

dataframes = []

for file in csv_files:
    file_path = os.path.join(input_file_path, file) 
    df = pd.read_csv(file_path) 
    dataframes.append(df)

In [84]:
df = pd.concat(dataframes, ignore_index=True)

In [69]:
# df = pd.read_csv(file_path)

In [85]:
df["Task Evidence"] = df["Task Evidence"].replace(["Null", "null"], pd.NA)
df = df[df["Task Evidence"].notna() & (df["Task Evidence"].str.strip() != "")]

In [86]:
print(df["Project Title"].unique())

["' BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प्रूवमेंट प्रोजेक्ट (2-1)'"
 "' Time and distance  प्रोजेक्ट (2-1)'" "' विद्युत मिलान संकेतिक यंत्र'"
 "' class 6th -Ham & Hamara paushtik aahar.   class 8- Aag se bachav.    class 7 - Jal hai to kal hai'"
 "' BH हमारे क्षेत्र का नक्शा  क्लास 8 math '"
 "' दहन और ज्वाला  आग से बचावBH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प्रूवमेंट प्रोजेक्ट (2-1)'"
 "'  जल है तो कल है। जल और जंगल। आग से बचाव:- दहन और ज्वाला, ईंधन:- हमारी जरूरत। '"
 "' PROJECT BASED LEARNING -  तड़ित और भूकंप '" "' sapno ka ganw'"
 "' sabse tej kaon BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प्रूवमेंट प्रोजेक्ट (2-1)'"]

In [87]:
# filtered_df = df[df['Project Title'] == "' BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प्रूवमेंट प्रोजेक्ट (2-1)'"]
project_list = [
    "BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प्रूवमेंट प्रोजेक्ट (2-1)",
    "BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प्रूवमेंट प्रोजेक्ट (2-2)",
    "BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प्रूवमेंट प्रोजेक्ट (2-3)"
]

In [88]:
df['Project Title'] = df['Project Title'].str.strip("' ")

In [89]:
filtered_df = df[df['Project Title'].isin(project_list)]

In [90]:
filtered_df['Project Title']

1        BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...
2        BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...
3        BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...
8        BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...
10       BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...
                               ...
53008    BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...
53009    BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...
53010    BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...
53011    BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...
53012    BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...
Name: Project Title, Length: 32943, dtype: object

In [91]:
# Further filter rows based on "Tasks" containing specific keywords and "Project completion date of the user"
filtered_tasks = filtered_df[
    (
        filtered_df["Tasks"].str.contains(r"शिक्षक कक्षा 6", na=False)
        | filtered_df["Tasks"].str.contains(r"शिक्षक कक्षा 7", na=False)
        | filtered_df["Tasks"].str.contains(r"शिक्षक कक्षा 8", na=False)
    )
    & (filtered_df["Project completion date of the user"] < "2024-11-01")
]

# Group by the specified columns and calculate the task count
grouped = (
    filtered_tasks
    .groupby([
        "Declared State",
        "Project Title",
        "District",
        "Block",
        "School Name",
        "School ID",
        "Tasks"
    ])
    .size()
    .reset_index(name="Taskcount")
)

In [92]:
grouped

,Declared State,Project Title,District,Block,School Name,School ID,Tasks,Taskcount
0,Bihar,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,Araria,ARARIA,PS MADAN PUR,10071202402,'3. शिक्षक कक्षा 7 के PBL विज्ञान की पहली पाठ ...,1
1,Bihar,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,Araria,ARARIA,PS MADAN PUR,10071202402,'4. शिक्षक कक्षा 8 के PBL विज्ञान की पहली पाठ ...,2
2,Bihar,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,Araria,ARARIA,PS MADAN PUR,10071202402,'6. शिक्षक कक्षा 7 के PBL गणित की पहली पाठ योज...,1
3,Bihar,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,Araria,ARARIA,PS MADAN PUR,10071202402,'7. शिक्षक कक्षा 8 के PBL गणित की पहली पाठ योज...,2
4,Bihar,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,Araria,ARARIA,UHS ARARIA BASTI,10071206601,'3. शिक्षक कक्षा 7 के PBL विज्ञान की पहली पाठ ...,6
...,...,...,...,...,...,...,...,...
12878,Bihar,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,W Champaran,Ramnagar,Govt. U.M.S. Bishunpurwa,10011204904,'6. शिक्षक कक्षा 7 के PBL गणित की पहली पाठ योज...,1
12879,Bihar,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,W Champaran,Ramnagar,Govt. U.M.S. Bishunpurwa,10011204904,'7. शिक्षक कक्षा 8 के PBL गणित की पहली पाठ योज...,1
12880,Null,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,Null,Null,Null,Null,'2. शिक्षक कक्षा 6 के PBL विज्ञान की पहली पाठ ...,5
12881,Null,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,Null,Null,Null,Null,'3. शिक्षक कक्षा 7 के PBL विज्ञान की पहली पाठ ...,4
12882,Null,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,Null,Null,Null,Null,'6. शिक्षक कक्षा 7 के PBL गणित की पहली पाठ योज...,1

In [95]:
print(grouped['Tasks'].unique())

["'3. शिक्षक कक्षा 7 के PBL विज्ञान की पहली पाठ योजना क्रियान्वित कर प्रस्तुतीकरण की तस्वीरें अथवा वीडियो अपलोड करें'"
 "'4. शिक्षक कक्षा 8 के PBL विज्ञान की पहली पाठ योजना क्रियान्वित कर प्रस्तुतीकरण की तस्वीरें अथवा वीडियो अपलोड करें'"
 "'6. शिक्षक कक्षा 7 के PBL गणित की पहली पाठ योजना क्रियान्वित कर प्रस्तुतीकरण की तस्वीरें अथवा वीडियो अपलोड करें'"
 "'7. शिक्षक कक्षा 8 के PBL गणित की पहली पाठ योजना क्रियान्वित कर प्रस्तुतीकरण की तस्वीरें अथवा वीडियो अपलोड करें'"
 "'2. शिक्षक कक्षा 6 के PBL विज्ञान की पहली पाठ योजना क्रियान्वित कर प्रस्तुतीकरण की तस्वीरें अथवा वीडियो अपलोड करें'"
 "'5. शिक्षक कक्षा 6 के PBL गणित की पहली पाठ योजना क्रियान्वित कर प्रस्तुतीकरण की तस्वीरें अथवा वीडियो अपलोड करें'"]

In [93]:
grouped_df = (
    grouped.groupby(
        ["Declared State", "Project Title", "District", "Block", "School Name", "School ID"], dropna=False
    )
    .size()
    .reset_index(name="TaskCount")
)

# Reordering the columns to match the SQL output structure
result_df = grouped_df[
    ["Project Title", "Declared State", "District", "Block", "School Name", "School ID", "TaskCount"]
]

In [79]:
result_df["TaskCount"].notnull()

Series([], Name: TaskCount, dtype: bool)

In [94]:
result_df

,Project Title,Declared State,District,Block,School Name,School ID,TaskCount
0,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,Bihar,Araria,ARARIA,PS MADAN PUR,10071202402,4
1,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,Bihar,Araria,ARARIA,UHS ARARIA BASTI,10071206601,2
2,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,Bihar,Araria,Bhargama,Ums Paikpar Muslim Tola,10072000203,6
3,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,Bihar,Araria,FORBISGANJ,MS SIMRAHA,10071804702,5
4,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,Bihar,Araria,Forbisganj,Ms Rang Daha Majhua,10071807601,6
...,...,...,...,...,...,...,...
2928,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,Bihar,W Champaran,Bagaha-I,Govt. U.M.S. Jamadar Tola,10010705101,3
2929,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,Bihar,W Champaran,Bagaha-I,Govt. U.M.S. Sirisia,10010710801,5
2930,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,Bihar,W Champaran,Bettiah,GOVT. M.S. MANSA TOLA (URDU),10010101701,4
2931,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,Bihar,W Champaran,Ramnagar,Govt. U.M.S. Bishunpurwa,10011204904,6
2932,BH_प्रोजेक्ट बेस्ड लर्निंग आधारित माइक्रो इम्प...,Null,Null,Null,Null,Null,3